plugins:
  - rubocop-performance
  - rubocop-rails

inherit_from: .rubocop_todo.yml

# Double negation is the most convenient way in Ruby to convert any value to boolean. Allow the use of it.
DoubleNegation:
  Enabled: false

WordArray:
  Enabled: false

AllCops:
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'client/node_modules/**/*'
    - 'vendor/bundle/**/*'
    - '.pryrc'
    - 'Procfile.spec'
  TargetRubyVersion: 3.2.2

Style/RegexpLiteral:
  Enabled: false

# This is enabled by default for Ruby 2.3. It's a good thing to do and
# should be enabled later but requires going through quite a bit of
# code.
Style/FrozenStringLiteralComment:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - app/services/persons/payment_settings_common.rb
    - app/services/persons/payment_settings_service.rb
    - app/helpers/payments_helper.rb
    - app/services/stripe_service/api/payments.rb
    - spec/controllers/admin/landing_page_versions/sections_controller_spec.rb
    - spec/controllers/admin2/design/landing_page_versions/sections_controller_spec.rb
    - spec/services/paypal_service/data_types/ipn_spec.rb
    - spec/services/transaction_service/process_spec.rb
    - spec/services/util_spec.rb
    - spec/utils/jwt_utils_spec.rb
    -
Rails/Delegate:
  Enabled: false

